<h3>Ressources</h3>
    <table>
        <tr>
            <td>Gold:</td>
            <td><?=$res['gold'];?></td>
        </tr>
        <tr>
            <td>Stone:</td>
            <td><?=$res['stone'];?></td>
        </tr>
        <tr>
            <td>Wood:</td>
            <td><?=$res['wood'];?></td>
        </tr>
        <tr>
            <td>Food:</td>
            <td><?=$res['food'];?></td>
        </tr>
        <tr>
            <td>Iron:</td>
            <td><?=$res['iron'];?></td>
        </tr>
        <tr>
            <td>Oil:</td>
            <td><?=$res['oil'];?></td>
        </tr>
        <tr>
            <td>Energy:</td>
            <td><?=$res['energy'];?></td>
        </tr>
    </table>